### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by randyzwitch** [davidanthoff/Electron.jl#3]
I might be missing something, but why not add a webserver? Is this just so you can pop a window open from the REPL and display HTML?

**Comment by davidanthoff** [comment]
Yes, this is just a thin wrapper for electron. You can certainly combine it with a web server if you want to, but there are lots of use cases where you don’t want to do that. So I think those things should better live in separate packages.

**Comment by randyzwitch** [comment]
Sounds like I need to do some RTFM with the Electron project. But yeah, way too much going on with web packages right now, I think I’m going to try something really stripped down.

**Comment by davidanthoff** [comment]
What are you trying to do? I have another package that pushes a display onto the display stack that then shows figures in an electron window, would that help?

**Comment by randyzwitch** [comment]
Just trying to understand the state of the ecosystem to be honest. ECharts will eventually inherit something, because I need JavaScript to save PNG files. But I also don't have a display from the REPL yet either (nor VSCode for that matter).

**Comment by davidanthoff** [comment]
So for both VS Code and ElectronDisplay.jl it is enough to add methods to ``show`` for a MIME type that these displays understands, and then everything should work.

**Comment by randyzwitch** [comment]
Is this Jupyter show method what you are talking about? It doesn’t currently work on VSCode, though it could be due to require.js https://github.com/randyzwitch/ECharts.jl/blob/master/src/render.jl

**Comment by davidanthoff** [comment]
We don't show MIME content of type ``text/html`` right now in VS Code because then we would also end up showing things like ``DataFrame`` in the plot pane.

Maybe the right strategy would be something similar to what we are doing with vega-lite: we could have a MIME type for echarts specs that just contains the necessary JSON that defines an echart, and then we handle all the details of the HTML generation in VS Code and ElectronDisplay?
